import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Key Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'key-concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Coverage',
      items: [
        {
          type: 'autogenerated',
          dirName: 'coverage',
        },
      ],
    },
    {
      type: 'category',
      label: 'IO',
      items: [
        {
          type: 'autogenerated',
          dirName: 'IO',
        },
      ],
    },
    {
      type: 'html',
      value: '<hr>',
      className: 'sidebar-separator',
    },
    {
      type: 'link',
      label: 'GitHub',
      href: 'https://github.com/Brale-xyz',
    },
    {
      type: 'link',
      label: 'Telegram',
      href: 'https://t.me/bralecommunity',
    },
  ],

  apiSidebar: [
    {
      type: 'doc',
      id: 'api/brale-issuance-and-orchestration-api',
    },
    {
      type: 'category',
      label: 'Accounts',
      items: [
        {
          type: 'doc',
          id: 'api/list-accounts',
          label: 'Retrieve all accounts',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-account',
          label: 'Create a customer account',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-account',
          label: 'Retrieve a customer account',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Transfers',
      items: [
        {
          type: 'doc',
          id: 'api/list-transfers',
          label: 'Get all transfers for a given account',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-transfer',
          label: 'Create a new transfer',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-transfer',
          label: 'Retrieve a single transfer',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Addresses',
      items: [
        {
          type: 'doc',
          id: 'api/list-addresses',
          label: 'Fetch all addresses',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-address',
          label: 'Create a new external address',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-address-balance',
          label: 'Fetch the balance of an internal (custodial) address for a specific token',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Financial Institutions',
      items: [
        {
          type: 'doc',
          id: 'api/list-financial-institutions',
          label: 'Fetch all financial institutions',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-financial-institution',
          label: 'Create a new external financial institution',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/get-financial-institution',
          label: 'Fetch a specific financial institution',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Automations',
      items: [
        {
          type: 'doc',
          id: 'api/create-automations',
          label: 'Create an Automation',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/list-automations',
          label: 'Fetch all automations for an account',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/get-automations',
          label: 'Retrieve a single automation',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Plaid',
      items: [
        {
          type: 'doc',
          id: 'api/create-a-plaid-link-token',
          label: 'Create a Plaid Link token',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/exchange-public-token-and-register-an-ach-debit-address',
          label: 'Exchange public_token and register an ACH-debit address',
          className: 'api-method post',
        },
      ],
    },
  ],
};

export default sidebars;
