import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Key Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'key-concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Coverage',
      items: [
        {
          type: 'autogenerated',
          dirName: 'coverage',
        },
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-specs',
    },
  ],
};

export default sidebars;
