import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  guideSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Key Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'key-concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Coverage',
      items: [
        {
          type: 'autogenerated',
          dirName: 'coverage',
        },
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'doc',
      id: 'api/brale-issuance-and-orchestration-api',
    },
    {
      type: 'category',
      label: 'Accounts',
      items: [
        {
          type: 'doc',
          id: 'api/retrieve-all-accounts',
          label: 'Retrieve all accounts',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-a-customer-account',
          label: 'Create a customer account',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/retrieve-a-customer-account',
          label: 'Retrieve a customer account',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Transfers',
      items: [
        {
          type: 'doc',
          id: 'api/get-all-transfers-for-a-given-account',
          label: 'Get all transfers for a given account',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-a-new-transfer',
          label: 'Create a new transfer',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/retrieve-a-single-transfer',
          label: 'Retrieve a single transfer',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Addresses',
      items: [
        {
          type: 'doc',
          id: 'api/fetch-all-addresses',
          label: 'Fetch all addresses',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-a-new-external-address',
          label: 'Create a new external address',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/fetch-the-balance-of-an-internal-custodial-address-for-a-specific-token',
          label: 'Fetch the balance of an internal (custodial) address for a specific token',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Financial Institutions',
      items: [
        {
          type: 'doc',
          id: 'api/fetch-all-financial-institutions',
          label: 'Fetch all financial institutions',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/create-a-new-external-financial-institution',
          label: 'Create a new external financial institution',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/fetch-a-specific-financial-institution',
          label: 'Fetch a specific financial institution',
          className: 'api-method get',
        },
      ],
    },
    {
      type: 'category',
      label: 'Automations',
      items: [
        {
          type: 'doc',
          id: 'api/create-an-automation',
          label: 'Create an Automation',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'api/fetch-all-automations-for-an-account',
          label: 'Fetch all automations for an account',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'api/retrieve-a-single-automation',
          label: 'Retrieve a single automation',
          className: 'api-method get',
        },
      ],
    },
  ],
};

export default sidebars;
