name: CI

on:
  push: { branches: [main] }
  pull_request:

env:
  FONT_AWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_NPM_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .tool-versions
      - run: npm ci
      - run: npm run format:check
      - run: npm run lint
