name: CI

on:
  push: { branches: [main] }
  pull_request:

env:
  FONT_AWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONT_AWESOME_NPM_AUTH_TOKEN }}

jobs:
  auto-format:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check if formatting is needed
        id: format-check
        run: |
          if ! npm run format:check; then
            echo "needs-formatting=true" >> $GITHUB_OUTPUT
          else
            echo "needs-formatting=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR with formatting instructions
        if: steps.format-check.outputs.needs-formatting == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🔧 Formatting Required

            This PR needs formatting. Please format your code before merging.

            **How to fix:**
            1. Edit the files in GitHub (click the pencil icon)
            2. Copy the content to [Prettier Playground](https://prettier.io/playground/)
            3. Format the code and copy it back
            4. Save and commit your changes

            **Or use these online tools:**
            - [Prettier Playground](https://prettier.io/playground/) - Format your code online
            - [ESLint Playground](https://eslint.org/play/) - Check for linting issues

            **Files that need formatting:**
            Check the workflow logs for specific files that failed formatting.`
            })

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .tool-versions
      - run: npm ci
      - run: npm run lint
      - run: npm run build
